# Generated by Django 5.0.6 on 2024-06-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course',
            new_name='education_module',
        ),
    ]
