# Generated by Django 5.0.6 on 2024-06-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='owner',
        ),
    ]
