# Generated by Django 5.0.6 on 2024-06-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_remove_lesson_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationmodule',
            name='owner',
        ),
    ]
