# Generated by Django 5.0.6 on 2024-06-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_educationmodule_owner_lesson_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationmodule',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='owner',
        ),
    ]
